apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30200
        hostPort: 30200
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp            # Optional, defaults to tcp
  - role: worker
