apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: powerapp-db-volume
  name: powerapp-db-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
