apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: stress-test
  name: stress-test
spec:
  template:
    spec:
      containers:
      - name: stress
        image: progrium/stress:latest
        command: ["/usr/bin/stress"]
        args:
        - "-c"
        - "3"
      restartPolicy: Never
  backoffLimit: 1
