apiVersion: v1
kind: Service
metadata:
  namespace: debug
  creationTimestamp: null
  labels:
    app: powerapp-backend-service
  name: powerapp-backend-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: powrapp-backend
