apiVersion: v1
kind: Service
metadata:
  namespace: debug
  labels:
    service: powerapp-web-service
  name: powerapp-web-service
spec:
  type: NodePort
  ports:
    - name: "web"
      port: 80
      protocol: TCP
  selector:
    app: powerapp_web
