apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secret-manager
spec:
  params:
    - name: CONJUR_API_KEY
      description: conjur rest api key
  steps:
    - name: retrieve-secret
      image: alpine:3.18.0
      script: |
        #!/usr/bin/env sh
        apk --no-cache add curl
        echo "Retrieving secret from Conjur..."
        TOKEN=$(curl -s --insecure -X POST --header "Accept-Encoding: base64" --data $(params.CONJUR_API_KEY) https://10.7.0.122/authn/default/host%2Fconjur%2Ftekton-pipeline-demo/authenticate)
        SECRET=$(curl -s --insecure -H "Authorization: Token token=\"$TOKEN\"" https://10.7.0.120/secrets/default/variable/secrets%2FTEST-VARIABLE-TEKTON-PIPELINE)
        echo "The secret value is: $SECRET"
