apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"] # remember the least privilege principle!
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-role-binding
subjects:
  - kind: ServiceAccount
    name: api-service-account
roleRef:
  kind: Role
  name: api-role
  apiGroup: rbac.authorization.k8s.io