apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traffic
spec:
  podSelector:
    matchLabels:
      app: sample-app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: allowed-app
