apiVersion: v1
kind: Service
metadata:
  labels:
    app: beautiful
  name: beautiful
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: beautiful
    version: v1
  type: NodePort
